# Pull Request や master, develop, リリースブランチを push した時に CI を実行する

name: CI

on:
  # push:
  #   branches: ['master', 'develop', 'release*']
  pull_request:
  # 動作確認用
  workflow_dispatch:

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo ${{ github.ref }}
