name: CI Dispatch

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-pull-request-ci]

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/ci-job.yml
    with:
      checkout-ref: 'refs/pull/${{ github.event.client_payload.pull_request_number }}/merge'
