name: CI Job

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      checkout-ref:
        required: true
        type: string

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout ${{ inputs.checkout-ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout-ref }}
      - name: error
        run: exit 1
