name: CI

on:
  workflow_dispatch:
  # push:
  #   branches: ['master', 'develop', 'release*']
  pull_request:
    types: ['opened']
    # branches: ['topic-module-upgrade-*']
    # paths: 'topic-module-upgrade-*'
  # workflow_run:
  #   workflows: ["Create PR"]
  #   types: [completed]
    # branches: ['topic-module-update-*']

jobs:
  call-workflow:
    uses: ./.github/workflows/ci-job.yml
    with:
      checkout-ref: ${{ github.ref }}
