name: CI

on:
  workflow_dispatch:
  push:
    branches: ['master', 'develop', 'release**', 'topic-module-upgrade-**']
  pull_request:
    types: ['opened', 'synchronize', 'reopened', 'ready_for_review']
    # branches: ['topic-module-upgrade-*']
    # paths: ['./update.txt']
  # pull_request_target:
    # types: ['opened', 'synchronize', 'reopened', 'ready_for_review']
  # workflow_run:
    # workflows: ["Create PR"]
    # types: [completed]
    # branches: ['topic-module-update-*']

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/ci-job.yml
    with:
      checkout-ref: ${{ github.ref }}
