name: Create PR

on:
  schedule:
    - cron: '0 0 25 * *'
  workflow_dispatch:

jobs:
  create-pr:
    name: Create Pull Request
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      TOPIC_BRANCH: ${{ steps.pr_val.outputs.TOPIC_BRANCH }}
      PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
    steps:
      - name: Checkout Default Branch
        uses: actions/checkout@v4
      - name: Set up Pull Request Variables
        id: pr_val
        run: |
          TIMESTAMP=$(date '+%Y%m%d%H%M%S')
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_OUTPUT
          echo "JOB_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
          echo "TOPIC_BRANCH=topic-module-upgrade-$TIMESTAMP" >> $GITHUB_OUTPUT
      - name: Create Commits
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "${{ steps.pr_val.outputs.TIMESTAMP }}" > ./update.txt
          git add ./update.txt
          git commit --allow-empty -m "【${{ steps.pr_val.outputs.TIMESTAMP }}】 テスト PR 作成"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          title: '【${{ steps.pr_val.outputs.TIMESTAMP }}】 テスト PR 作成'
          branch: '${{ steps.pr_val.outputs.TOPIC_BRANCH }}'
          draft: false
          base: develop
          delete-branch: true
          body: |
            ## 関連 URL

            - 省略
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
  # refs/heads/{BRANCH_NAME}
  # refs/pull/{PULL_REQUESTNUMBER}/merge
  # call-workflow:
  #   needs: ['create-pr']
  #   uses: ./.github/workflows/ci-job.yml
  #   with:
  #     # checkout-ref: 'refs/heads/${{ needs.create-pr.outputs.TOPIC_BRANCH }}'
  #     checkout-ref: 'refs/pull/${{ needs.create-pr.outputs.PR_NUMBER }}/merge'
  run-workflow:
    needs: ['create-pr']
    name: Run Workflow
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Run Workflow
        run: |
          gh workflow run 'CI' --ref 'refs/pull/${{ needs.create-pr.outputs.PR_NUMBER }}/merge'